'use client';

import Link from 'next/link';
import { Suspense, useCallback, useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, Clock3, FileText, Loader2, PackageCheck, RefreshCw, Truck, WalletCards } from 'lucide-react';
import { useSearchParams } from 'next/navigation';
import { useSession } from '@/components/AuthProvider';

const STAGES = ['TRIAGED', 'WORKING', 'QUOTATION', 'WAITING_FOR_DEALER', 'CONFIRMED', 'PAYMENT_PENDING', 'ALLOCATED', 'DISPATCH_PENDING', 'DISPATCHED', 'DELIVERED', 'CLOSED', 'ON_HOLD', 'ESCALATED', 'LOST', 'CANCELLED'];
const title = (value) => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const date = (value) => value ? new Date(value).toLocaleDateString() : '—';
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN')}`;

function Board({ data, loading, error }) {
  const totals = data?.totals || {};
  const cards = [
    ['Payment pending', totals.paymentPending, WalletCards, 'text-amber-700'], ['Allocated', totals.allocated, PackageCheck, 'text-indigo-700'],
    ['Dispatch pending', totals.dispatchPending, Truck, 'text-blue-700'], ['Overdue dispatch', totals.overdueDispatch, AlertTriangle, 'text-rose-700'],
  ];
  return <>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <div key={label} className="rounded-xl border border-border bg-white p-4 shadow-sm"><div className="flex items-center justify-between text-xs text-muted"><span>{label}</span><Icon className={`h-4 w-4 ${color}`} /></div><p className="mt-2 text-2xl font-bold text-foreground">{loading ? '—' : Number(value || 0)}</p></div>)}</div>
    <div className="mt-5 overflow-hidden rounded-xl border border-border bg-white shadow-sm">{error ? <div className="p-5 text-sm text-rose-700">{error}</div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-border bg-slate-50 text-xs text-muted"><tr><th className="px-4 py-3">Dealer / order</th><th className="px-4 py-3">Workflow</th><th className="px-4 py-3">Dispatch commitment</th><th className="px-4 py-3">LR/Bilty</th><th className="px-4 py-3"></th></tr></thead><tbody>{loading ? <tr><td colSpan="5" className="px-4 py-10 text-center text-muted"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></td></tr> : (data?.rows || []).length === 0 ? <tr><td colSpan="5" className="px-4 py-10 text-center text-muted">No dealer orders currently require fulfillment.</td></tr> : data.rows.map((row) => <tr key={row.inquiryId} className="border-b border-border last:border-0"><td className="px-4 py-3"><p className="font-semibold text-foreground">{row.dealer?.businessName || 'Dealer review required'}</p><p className="text-xs text-muted">{row.order?.displayId} · {money(row.order?.total)}</p></td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{title(row.stage)}</span><p className="mt-1 text-xs text-muted">{row.order?.fulfillmentGodown?.name || 'Godown not allocated'}</p></td><td className="px-4 py-3"><p>{date(row.order?.expectedDispatchDate)}</p><p className={`text-xs ${row.order?.countdown?.state === 'OVERDUE' ? 'text-rose-700' : 'text-muted'}`}>{row.order?.countdown?.label || 'Dispatch date not committed'}</p></td><td className="px-4 py-3">{row.order?.logisticReceiptUrl ? <a href={row.order.logisticReceiptUrl} target="_blank" rel="noreferrer" className="text-xs font-semibold text-accent hover:underline">View {row.order.lrNumber || 'receipt'}</a> : <span className="text-xs text-amber-700">Pending</span>}</td><td className="px-4 py-3"><Link href={`/routing-crm/fulfillment?group_id=${encodeURIComponent(row.group?.id || '')}`} className="text-xs font-semibold text-accent hover:underline">Open workflow</Link></td></tr>)}</tbody></table></div>}</div>
  </>;
}

function Workflow({ groupId, session }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const [reason, setReason] = useState(''); const [stage, setStage] = useState(''); const [expectedDispatchDate, setExpectedDispatchDate] = useState(''); const [payment, setPayment] = useState({ amount: '', reference: '', method: 'UPI' }); const [allocation, setAllocation] = useState({ godownId: '', allocationNotes: '' }); const [dispatch, setDispatch] = useState({ transporterName: '', transportContact: '', lrNumber: '', expectedDeliveryDate: '', dispatchNotes: '', receipt: null });
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/evolution/groups/${encodeURIComponent(groupId)}/fulfillment`, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to load fulfillment workflow'); setData(body.data); setStage(body.data.inquiry.stage); } catch (error) { setNotice(error.message || 'Unable to load workflow'); } finally { setLoading(false); } }, [groupId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function act(action, values = {}, file = null) { setBusy(true); setNotice(''); try { let response; if (file) { const form = new FormData(); Object.entries({ action, expectedVersion: data.ticket.version, reason, ...values }).forEach(([key, value]) => form.set(key, String(value ?? ''))); form.set('receipt', file); response = await fetch(`/api/evolution/groups/${encodeURIComponent(groupId)}/fulfillment`, { method: 'POST', body: form }); } else response = await fetch(`/api/evolution/groups/${encodeURIComponent(groupId)}/fulfillment`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, expectedVersion: data.ticket.version, reason, ...values }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to update fulfillment workflow'); setReason(''); setNotice('Saved.'); await load(); } catch (error) { setNotice(error.message || 'Unable to update fulfillment workflow'); } finally { setBusy(false); } }
  async function createOrder() { setBusy(true); setNotice(''); try { const response = await fetch(`/api/evolution/groups/${encodeURIComponent(groupId)}/convert`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ notes: reason, expectedDispatchDate, expectedVersion: data.ticket.version }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to create dealer order'); setNotice(`Dealer-order draft ${body.data.order.displayId} created. Add priced product line items in Dealers & Partners before fulfillment.`); await load(); } catch (error) { setNotice(error.message || 'Unable to create dealer order'); } finally { setBusy(false); } }
  if (loading) return <div className="flex justify-center p-10"><Loader2 className="h-6 w-6 animate-spin text-accent" /></div>;
  if (!data) return <p className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{notice || 'Workflow unavailable.'}</p>;
  const order = data.order; const isManager = ['ADMIN', 'MANAGER'].includes(session?.user?.role); const department = String(session?.user?.routingDepartment?.name || '').toLowerCase(); const sales = isManager || department === 'sales'; const accounts = isManager || department === 'accounts'; const warehouse = isManager || department === 'warehouse' || department === 'godown'; const logistics = isManager || department === 'logistics';
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/routing-crm/fulfillment" className="inline-flex items-center gap-1 text-xs font-semibold text-accent"><ArrowLeft className="h-3.5 w-3.5" />Fulfillment Board</Link><h1 className="mt-2 text-2xl font-bold text-foreground">{data.group.subject}</h1><p className="mt-1 text-sm text-muted">{data.inquiry.dealer?.businessName || 'Dealer link required'} · {title(data.inquiry.stage)}</p></div>{order && <div className="rounded-xl border border-border bg-white px-4 py-3 text-right"><p className="text-xs text-muted">{order.displayId}</p><p className="font-bold">{money(order.total)}</p><p className={`text-xs ${order.countdown?.state === 'OVERDUE' ? 'text-rose-700' : 'text-muted'}`}>{order.countdown?.label}</p></div>}</div>
    {notice && <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{notice}</div>}
    <section className="rounded-xl border border-border bg-white p-5"><h2 className="font-semibold">Lifecycle</h2><p className="mt-1 text-sm text-muted">Every change is version-checked and recorded in the ticket audit trail.</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_2fr_auto]"><select value={stage} onChange={(event) => setStage(event.target.value)} className="rounded-lg border border-border px-3 py-2 text-sm">{STAGES.map((item) => <option key={item} value={item}>{title(item)}</option>)}</select><input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason for the transition" className="rounded-lg border border-border px-3 py-2 text-sm" /><button disabled={busy || !reason.trim()} onClick={() => act('transition', { stage })} className="rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Update stage</button></div>{!order && sales && data.inquiry.stage === 'CONFIRMED' && <div className="mt-3 flex flex-wrap items-end gap-2 rounded-lg bg-slate-50 p-3"><label className="text-xs font-medium text-muted">Committed dispatch date<input type="date" value={expectedDispatchDate} min={new Date().toISOString().slice(0, 10)} onChange={(event) => setExpectedDispatchDate(event.target.value)} className="mt-1 block rounded border border-border bg-white px-2 py-1.5 text-sm text-foreground" /></label><button disabled={busy || !expectedDispatchDate} onClick={createOrder} className="rounded-lg border border-accent px-3 py-2 text-sm font-semibold text-accent disabled:opacity-50">Create dealer-order draft</button><p className="basis-full text-xs text-muted">The draft cannot be paid, allocated, or dispatched until priced product line items are added.</p></div>}</section>
    {order && <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-xl border border-border bg-white p-5"><WalletCards className="h-5 w-5 text-amber-700" /><h2 className="mt-2 font-semibold">Payment verification</h2><p className="mt-1 text-xs text-muted">Paid {money(order.amountPaid)} · balance {money(order.balanceDue)}</p>{accounts && <div className="mt-3 space-y-2"><input type="number" min="1" value={payment.amount} onChange={(event) => setPayment({ ...payment, amount: event.target.value })} placeholder="Received amount" className="w-full rounded-lg border border-border px-3 py-2 text-sm" /><input value={payment.reference} onChange={(event) => setPayment({ ...payment, reference: event.target.value })} placeholder="UPI / bank reference" className="w-full rounded-lg border border-border px-3 py-2 text-sm" /><button disabled={busy || !payment.reference.trim()} onClick={() => act('payment_verified', payment)} className="w-full rounded-lg bg-amber-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Verify payment</button></div>}</section>
      <section className="rounded-xl border border-border bg-white p-5"><PackageCheck className="h-5 w-5 text-indigo-700" /><h2 className="mt-2 font-semibold">Warehouse allocation</h2><p className="mt-1 text-xs text-muted">{order.fulfillmentGodown?.name || 'No godown or lot recorded'}</p>{warehouse && <div className="mt-3 space-y-2"><input type="number" min="1" value={allocation.godownId} onChange={(event) => setAllocation({ ...allocation, godownId: event.target.value })} placeholder="Godown ID" className="w-full rounded-lg border border-border px-3 py-2 text-sm" /><textarea value={allocation.allocationNotes} onChange={(event) => setAllocation({ ...allocation, allocationNotes: event.target.value })} placeholder="Lot / slab / box and shade details" className="min-h-20 w-full rounded-lg border border-border px-3 py-2 text-sm" /><button disabled={busy || !allocation.godownId || !allocation.allocationNotes.trim()} onClick={() => act('allocate', allocation)} className="w-full rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Confirm allocation</button></div>}</section>
      <section className="rounded-xl border border-border bg-white p-5"><Truck className="h-5 w-5 text-blue-700" /><h2 className="mt-2 font-semibold">Dispatch & Bilty</h2><p className="mt-1 text-xs text-muted">{order.lrNumber ? `${order.transporterName || 'Transport'} · LR ${order.lrNumber}` : 'Transport details pending'}</p>{logistics && <div className="mt-3 space-y-2"><input value={dispatch.transporterName} onChange={(event) => setDispatch({ ...dispatch, transporterName: event.target.value })} placeholder="Transporter name" className="w-full rounded-lg border border-border px-3 py-2 text-sm" /><input value={dispatch.lrNumber} onChange={(event) => setDispatch({ ...dispatch, lrNumber: event.target.value })} placeholder="LR / Bilty number" className="w-full rounded-lg border border-border px-3 py-2 text-sm" /><input type="file" accept="image/*,application/pdf" onChange={(event) => setDispatch({ ...dispatch, receipt: event.target.files?.[0] || null })} className="w-full text-xs" /><button disabled={busy || !dispatch.transporterName || !dispatch.lrNumber || !dispatch.receipt} onClick={() => act('dispatch', dispatch, dispatch.receipt)} className="w-full rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Record dispatch</button>{data.inquiry.stage === 'DISPATCHED' && <button disabled={busy} onClick={() => act('deliver')} className="w-full rounded-lg border border-blue-600 px-3 py-2 text-sm font-semibold text-blue-700 disabled:opacity-50">Mark delivered</button>}</div>}</section></div>}
    <section className="rounded-xl border border-border bg-white p-5"><h2 className="font-semibold">Fulfillment audit</h2><div className="mt-3 space-y-2">{data.events.length === 0 ? <p className="text-sm text-muted">No fulfillment events yet.</p> : data.events.map((event) => <div key={event.id} className="flex items-start justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm"><div><p className="font-medium">{title(event.action)}</p><p className="text-xs text-muted">{event.note || `${title(event.fromStage)} → ${title(event.toStage)}`}</p></div><span className="shrink-0 text-xs text-muted">{new Date(event.createdAt).toLocaleString()}</span></div>)}</div></section>
  </div>;
}

function FulfillmentContent() {
  const params = useSearchParams(); const groupId = params.get('group_id'); const { data: session } = useSession(); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch('/api/evolution/fulfillment', { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to load fulfillment board'); setData(body.data); setError(''); } catch (err) { setError(err.message || 'Unable to load fulfillment board'); } finally { setLoading(false); } }, []);
  useEffect(() => { if (groupId) return undefined; const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [groupId, load]);
  if (groupId) return <Workflow groupId={groupId} session={session} />;
  return <div className="space-y-5 p-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-foreground">Dealer Fulfillment Board</h1><p className="mt-1 text-sm text-muted">Payment, allocation, dispatch commitments, and Bilty/LR completion from dealer group inquiries.</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border border-border bg-white px-3 py-2 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div><Board data={data} loading={loading} error={error} /></div>;
}

export default function FulfillmentPage() {
  return <Suspense fallback={<div className="flex justify-center p-10"><Loader2 className="h-6 w-6 animate-spin text-accent" /></div>}><FulfillmentContent /></Suspense>;
}
