'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileSpreadsheet, Loader2, RefreshCw, ScanSearch, Search, Send, ShieldCheck } from 'lucide-react';
import { useSession } from '@/components/AuthProvider';

function CatalogWorkspace() {
  const [sources, setSources] = useState([]); const [groups, setGroups] = useState([]); const [lotMedia, setLotMedia] = useState([]); const [health, setHealth] = useState(null); const [sourceUrl, setSourceUrl] = useState(''); const [sheetName, setSheetName] = useState('');
  const [groupId, setGroupId] = useState(''); const [query, setQuery] = useState(''); const [items, setItems] = useState([]); const [selected, setSelected] = useState([]); const [drafts, setDrafts] = useState([]); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const selectedItems = useMemo(() => items.filter((item) => selected.includes(item.id)), [items, selected]);
  const load = useCallback(async () => {
    setLoading(true); try {
      const [sourcesResponse, groupsResponse, healthResponse, mediaResponse] = await Promise.all([fetch('/api/evolution/catalog/sources', { cache: 'no-store' }), fetch('/api/evolution/groups', { cache: 'no-store' }), fetch('/api/evolution/observability', { cache: 'no-store' }), fetch('/api/evolution/vision/media', { cache: 'no-store' })]);
      const [sourcesBody, groupsBody, healthBody, mediaBody] = await Promise.all([sourcesResponse.json(), groupsResponse.json(), healthResponse.json(), mediaResponse.json()]);
      if (!sourcesResponse.ok) throw new Error(sourcesBody.error || 'Unable to load catalog sources'); if (!groupsResponse.ok) throw new Error(groupsBody.error || 'Unable to load dealer groups');
      setSources(sourcesBody.data || []); setGroups((groupsBody.data || []).filter((group) => group.inquiry?.dealerId)); setLotMedia(mediaResponse.ok ? mediaBody.data || [] : []); setHealth(healthResponse.ok ? healthBody.data : null); setNotice('');
    } catch (error) { setNotice(error.message || 'Unable to load catalog automation'); } finally { setLoading(false); }
  }, []);
  const loadDrafts = useCallback(async (id) => { if (!id) { setDrafts([]); return; } const response = await fetch(`/api/evolution/catalog/drafts?group_id=${encodeURIComponent(id)}`, { cache: 'no-store' }); const body = await response.json(); if (response.ok) setDrafts(body.data || []); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const timer = window.setTimeout(() => void loadDrafts(groupId), 0); return () => window.clearTimeout(timer); }, [groupId, loadDrafts]);
  async function addSource(event) { event.preventDefault(); setBusy(true); setNotice(''); try { const response = await fetch('/api/evolution/catalog/sources', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sourceUrl, sheetName }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to save source'); setSourceUrl(''); setSheetName(''); setNotice('Catalog source saved. Click Sync now to import its published CSV.'); await load(); } catch (error) { setNotice(error.message || 'Unable to save source'); } finally { setBusy(false); } }
  async function syncSource(id) { setBusy(true); setNotice(''); try { const response = await fetch(`/api/evolution/catalog/sources/${encodeURIComponent(id)}/sync`, { method: 'POST' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Catalog sync failed'); setNotice(`Sync complete: ${body.data.importedCount} imported, ${body.data.unchangedCount} unchanged, ${body.data.conflictCount} protected CRM conflicts, ${body.data.errorCount} skipped.`); await load(); } catch (error) { setNotice(error.message || 'Catalog sync failed'); } finally { setBusy(false); } }
  async function indexLotMedia(id) { setBusy(true); setNotice(''); try { const response = await fetch('/api/evolution/vision/media', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ lotMediaId: id }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to queue image indexing'); setNotice('Lot image queued for local indexing. It will become available for visual matching after the worker completes.'); } catch (error) { setNotice(error.message || 'Unable to queue image indexing'); } finally { setBusy(false); } }
  async function search(event) { event.preventDefault(); if (!groupId || query.trim().length < 2) return; setBusy(true); setNotice(''); try { const response = await fetch(`/api/evolution/catalog/search?group_id=${encodeURIComponent(groupId)}&q=${encodeURIComponent(query.trim())}`, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Catalog lookup failed'); setItems(body.data.items || []); setSelected([]); setNotice(body.data.exactCodeMatch ? 'Exact dealer-shareable SKU match found.' : 'Showing dealer-shareable catalog matches.'); } catch (error) { setNotice(error.message || 'Catalog lookup failed'); } finally { setBusy(false); } }
  async function createDraft() { if (!groupId || !selected.length) return; setBusy(true); setNotice(''); try { const response = await fetch('/api/evolution/catalog/drafts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ groupId, catalogItemIds: selected, confidence: items.length && selected.length ? 1 : 0.5 }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to create review draft'); setNotice('Dealer response draft created. It requires manager approval before sending.'); setSelected([]); await loadDrafts(groupId); } catch (error) { setNotice(error.message || 'Unable to create review draft'); } finally { setBusy(false); } }
  async function draftAction(id, action) { setBusy(true); setNotice(''); try { const response = await fetch(`/api/evolution/catalog/drafts/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || `Unable to ${action} draft`); setNotice(action === 'send' ? 'Approved catalog response sent to the WhatsApp group.' : `Draft ${action}d.`); await loadDrafts(groupId); } catch (error) { setNotice(error.message || `Unable to ${action} draft`); } finally { setBusy(false); } }
  return <div className="space-y-5 p-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-foreground">Catalog Automation</h1><p className="mt-1 text-sm text-muted">Published Google Sheet sync, dealer-tier lookup, and approval-gated WhatsApp catalog responses.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-border bg-white px-3 py-2 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div>{notice && <div className="flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><AlertTriangle className="h-4 w-4 shrink-0" />{notice}</div>}{health && <section className="grid gap-3 rounded-xl border border-border bg-white p-4 text-sm shadow-sm md:grid-cols-4"><div><p className="text-xs text-muted">Catalog queue</p><p className="font-semibold">{health.queues.catalogSync.waiting || 0} waiting · {health.queues.catalogSync.failed || 0} failed</p></div><div><p className="text-xs text-muted">Vision queue</p><p className="font-semibold">{health.vision.enabled ? `${health.queues.vision.waiting || 0} waiting` : 'Disabled safely'}</p></div><div><p className="text-xs text-muted">Worker latency</p><p className="font-semibold">{health.averageWorkerLatencyMs ? `${health.averageWorkerLatencyMs} ms` : 'No completed jobs yet'}</p></div><div><p className="text-xs text-muted">Catalog freshness</p><p className="font-semibold">{health.catalog.staleSourceIds.length ? `${health.catalog.staleSourceIds.length} source(s) need sync` : 'Up to date'}</p></div></section>}
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border border-border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-semibold"><FileSpreadsheet className="h-4 w-4 text-accent" />Catalog sources</h2><p className="mt-1 text-xs text-muted">Only published, read-only HTTPS Google Sheets CSV/export links are accepted. Sync never overwrites CRM pricing or stock.</p><form onSubmit={addSource} className="mt-4 space-y-2"><input required type="url" value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} placeholder="https://docs.google.com/spreadsheets/d/.../export?format=csv" className="w-full rounded-lg border border-border px-3 py-2 text-sm" /><input value={sheetName} onChange={(event) => setSheetName(event.target.value)} placeholder="Optional sheet label" className="w-full rounded-lg border border-border px-3 py-2 text-sm" /><button disabled={busy || !sourceUrl} className="rounded-lg bg-accent px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Add catalog source</button></form><div className="mt-4 space-y-2">{sources.length === 0 ? <p className="text-sm text-muted">No catalog source configured.</p> : sources.map((source) => <div key={source.id} className="rounded-lg border border-border p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{source.sheetName || 'Google Sheet catalog'}</p><p className="truncate text-xs text-muted">{source.sourceUrl}</p><p className="mt-1 text-xs text-muted">{source._count?.items || 0} rows · last success {source.lastSuccessAt ? new Date(source.lastSuccessAt).toLocaleString() : 'never'}</p>{source.syncs?.[0]?.errorSummary && <p className="mt-1 text-xs text-rose-700">{source.syncs[0].errorSummary}</p>}</div><button onClick={() => void syncSource(source.id)} disabled={busy} className="shrink-0 rounded border border-border px-2 py-1 text-xs font-semibold disabled:opacity-50">Sync now</button></div></div>)}</div></section>
      <section className="rounded-xl border border-border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-emerald-700" />Dealer-safe lookup</h2><p className="mt-1 text-xs text-muted">Rates are filtered to the linked dealer’s price tier. Every response remains a draft until approved.</p><form onSubmit={search} className="mt-4 space-y-2"><select required value={groupId} onChange={(event) => { setGroupId(event.target.value); setItems([]); setSelected([]); setQuery(''); }} className="w-full rounded-lg border border-border px-3 py-2 text-sm"><option value="">Select linked dealer group</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.subject} — {group.inquiry?.dealer?.businessName || 'Dealer'}</option>)}</select><div className="flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="SKU/code, marble name, size…" className="min-w-0 flex-1 rounded-lg border border-border px-3 py-2 text-sm" /><button disabled={busy || !groupId || query.trim().length < 2} className="inline-flex items-center gap-1 rounded-lg bg-slate-800 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><Search className="h-4 w-4" />Find</button></div></form><div className="mt-4 space-y-2">{items.map((item) => <label key={item.id} className="block cursor-pointer rounded-lg border border-border p-3 hover:bg-slate-50"><div className="flex gap-2"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id].slice(0, 3))} /><div className="min-w-0"><p className="text-sm font-semibold">{item.name} <span className="text-muted">({item.sku})</span></p><p className="text-xs text-muted">{[item.materialCategory, item.tileSize, item.finish, item.lotNumber && `Lot ${item.lotNumber}`, item.availableQuantity != null && `${item.availableQuantity} ${item.unitOfMeasure || ''}`, item.dealerRate != null && `₹${item.dealerRate}/${item.unitOfMeasure || 'unit'}`].filter(Boolean).join(' · ')}</p></div></div></label>)}{items.length > 0 && <button type="button" disabled={busy || !selectedItems.length} onClick={() => void createDraft()} className="mt-2 inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4" />Create approval draft ({selectedItems.length})</button>}</div></section></div>
    {groupId && <section className="rounded-xl border border-border bg-white p-5 shadow-sm"><h2 className="font-semibold">Catalog response review</h2><p className="mt-1 text-xs text-muted">An approved response can be sent once. Sending never reserves stock; Warehouse allocation is still required.</p><div className="mt-3 space-y-2">{drafts.length === 0 ? <p className="text-sm text-muted">No catalog response drafts for this group.</p> : drafts.map((draft) => <div key={draft.id} className="rounded-lg border border-border p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="whitespace-pre-wrap text-sm">{draft.content}</p><p className="mt-2 text-xs text-muted">{draft.status} · {new Date(draft.createdAt).toLocaleString()}</p></div><div className="flex gap-2">{draft.status === 'DRAFT' && <button disabled={busy} onClick={() => void draftAction(draft.id, 'approve')} className="rounded bg-emerald-700 px-2 py-1 text-xs font-semibold text-white disabled:opacity-50">Approve</button>}{draft.status === 'APPROVED' && <button disabled={busy} onClick={() => void draftAction(draft.id, 'send')} className="inline-flex items-center gap-1 rounded bg-accent px-2 py-1 text-xs font-semibold text-white disabled:opacity-50"><Send className="h-3 w-3" />Send</button>}</div></div></div>)}</div></section>}
  </div>;
}

export default function CatalogAutomationPage() {
  const { data: session, status } = useSession();
  if (status === 'loading') return <div className="flex min-h-[240px] items-center justify-center text-sm text-muted"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading access…</div>;
  const canManage = session?.user?.role === 'ADMIN' || session?.user?.role === 'MANAGER';
  if (!canManage) return <div className="mx-auto max-w-xl rounded-xl border border-amber-200 bg-amber-50 p-6 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-amber-700" /><h1 className="mt-3 text-lg font-bold text-foreground">Catalog Automation is manager-only</h1><p className="mt-2 text-sm text-muted">Your department inbox remains available. Ask an Admin or Manager to review catalog sources, dealer pricing, or visual matches.</p></div>;
  return <CatalogWorkspace />;
}
